# Reference: Provide an identity to access the Azure Key Vault Provider for Secrets Store CSI Driver
# Chapter: Use a user-assigned managed identity https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access?WT.mc_id=AZ-MVP-5003548#use-a-user-assigned-managed-identity

{{- range $key, $value := .Values.secrets }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $value.name }}
  namespace: {{ $value.namespace }}
spec:
  provider: azure
  parameters:
  {{ if $value.usePodIdentity }}
    usePodIdentity: "{{ $value.usePodIdentity }}"
  {{ else }}
    usePodIdentity: "{{ $.Values.usePodIdentity }}"
  {{ end }}
  {{ if $value.useVMManagedIdentity }}
    useVMManagedIdentity: "{{ $value.useVMManagedIdentity }}"
  {{ else }}
    useVMManagedIdentity: "{{ $.Values.useVMManagedIdentity }}"
  {{ end }}
    userAssignedIdentityID: {{ $.Values.userAssignedIdentityID }}
  {{ if $value.keyvaultName }}
    keyvaultName: {{ $value.keyvaultName }}
  {{ else }}
    keyvaultName: {{ $.Values.keyvaultName }}
  {{ end }}
    objects: |
      {{- $value.parameters.objects | nindent 6 }}
    tenantId: {{ $.Values.tenantId }}
{{ if $value.secretObjects }}
  secretObjects: {{ $value.secretObjects | toYaml | nindent 2 -}}
{{ end }}
---
{{- end }}
